print("Welcome to the tip calculator.")
bill = input("What was the total bill?")
tip = input("What percent tip would you like to leave?.")
people = input("How many people are splitting the bill?")
flt_bill = float(bill)
flt_tip = float(tip)
new_people = int(people)
pct = (flt_tip / 100)
tip_add = (flt_bill * pct)
new_bill = (flt_bill + tip_add)
final_split = round(new_bill / new_people, 2)
end_split = "{:.2f}".format(final_split)
result = (f"Each person should pay ${end_split}")
print(result)